config/routes.rb
Rails.application.routes.draw do
  get 'scanner/index'
  resources 'categories'
  resources 'products'
  resources 'appoitments'
  get 'home/products'
  get 'home/messages'
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  get '/offline.html' => "service_worker#offline"
  root to: "appoitments#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appoitment.rb
class Appoitment < ApplicationRecord
  STORES=[["Elektra, Ciudad de México", "1"],["Elektra Tacuba 1 Ciudad de México","2"], ["Elektra Tacuba Miguel Schultz
  Ciudad de México", "3"]]
end

app/controllers/application_controller.rb
require 'net/http'
require 'json'
class ApplicationController < ActionController::Base

  def gt_data(url_from)
    url = url_from
    uri = URI(url)
    response = Net::HTTP.get(uri)
    response['Content-Type']
    response['application/json']
    p "==============="
    @data = JSON.parse(response)
  end

end

app/controllers/appoitments_controller.rb
class AppoitmentsController < ApplicationController
  before_action :set_appoitment, only: [:show]
  
  def new
    @appoitment = Appoitment.new
  end

  def create
    @appoitment= Appoitment.new(params_appoitment)
    if @appoitment.save
      redirect_to root_path
    else
      p @appoitment.errors.full_messages
    end
  end

  def index
     @appoitments = Appoitment.all
  end

  def show

  end

  private
    def params_appoitment
      params.require(:appoitment).permit(:subject, :description)
    end

    def set_appoitment
      @appoitment = Appoitment.find(params[:id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = gt_data("https://challenge.ektdevelopers.com/api/catalog_system/pvt/category/tree/320/")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @data = gt_data("https://challenge.ektdevelopers.com/api/catalog_system/pvt/category/tree/320/")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = gt_data("https://challenge.ektdevelopers.com/api/catalog_system/pvt/products/GetProductAndSkuIds?categoryId=#{params['category_id']}&_from=1&_to=10")
        @products_list = []
        @products['data'].each do |product_id|
            product = gt_data("https://challenge.ektdevelopers.com/api/catalog_system/pvt/products/ProductGet/#{product_id[0]}")
            if !product.empty? && !product.nil?
                @products_list.push(product)
            end
        end
    end
  
  def show
    id= params[:id]
    @product = gt_data("https://challenge.ektdevelopers.com/api/catalog_system/pvt/products/#{id}/specification")
  end
end

app/controllers/scanner_controller.rb
class ScannerController < ApplicationController
  def index
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery except: :service_worker

  def service_worker
  end

  def manifest
  end

  def offline
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_menu_left
    default = capture do
      link_to 'https://www.elektra.com.mx/', "aria-label": "Inicio" do
        image_tag("elektra.svg")
      end
    end
    content_for(:header_menu_left) || default
  end

  def header_menu_right
    default = capture do
      link_to root_path, "aria-label": "Inicio" do
        image_tag("vink-70x22.png", height: "22px")
      end
    end

    content_for(:header_menu_right) || default
  end

  def header_title
    content_for(:header_title)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/scanner_helper.rb
module ScannerHelper
end

app/helpers/service_worker_helper.rb
module ServiceWorkerHelper
end

app/views/appoitments/index.html.erb
<h1>Listado de citas</h1>
<h1><%= Appoitment::STORES[0][0] %></h1>
<% @appoitments.each do |appoitment| %>
  <div class="column is-centered">
    <p class="has-background-light">
      <%= link_to appoitment_path(appoitment), class: "link" do %>
        <%= appoitment.subject %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/appoitments/new.html.erb
<h1>Agendar una cita</h1>
<%= form_for @appoitment, as: :appoitment , url: appoitments_path, method: :post do |l| %>
  <div class="field">
    <%= l.label "Asunto", class: "label" %>
    <div class= "control">
      <%= l.text_field :subject, class: "input" %>
    </diV>
  </div>
  <div class= "field">
    <%= l.label "Descripción", class: "label" %>
    <div class= "control">
      <%= l.text_area :description, class: "textarea" %>
    </div>
  </div>
  <div class="col-md-12 text-center">
    <%= l.submit "Guardar", class: "button"%>
  </div>
<% end %>

app/views/appoitments/show.html.erb
<div class= "body">
  <h1 style="border: 1px yellow solid" >
    <%= @appoitment.subject %>
  </h1>
  <p>
    <%= @appoitment.description %>
  </p>
  <p align="right">Tienda: <%= Appoitment::STORES[0][0] %></p>
</div>

app/views/categories/index.html.erb
<%- content_for( :categories_selected ) { "selected" } %>
<%- content_for( :footer ) {  } %>
<%- content_for( :header_menu_left ) { } %>
<%- content_for( :header_menu_rught ) { } %>

<aside class="menu">
  <% @data.each do |name| %>
    <% if name['children'].count > 0 %>
      <p class="menu-label">
        <%= name['name'] %>
      </p>
      <ul class="menu-list">
        <% name['children'].each do |subname| %>
          <% if subname['children'].count > 0 %>
            <li>
              <a><%= subname['name']%></a>
              <ul>
                <% subname['children'].each do |minimalname| %>
                  <li>
                    <%= link_to products_path(category_id: minimalname['id']) do %>
                      <%= minimalname['name']%>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</aside>

app/views/home/appointments.html.erb
<h1>Home#appointments</h1>
<p>Find me in app/views/home/appointments.html.erb</p>}

app/views/home/index.html.erb
<%- content_for( :categories_selected ) { "selected" } %>
<%- content_for( :footer ) {  } %>
<%- content_for( :header_menu_left ) { } %>
<%- content_for( :header_menu_rught ) { } %>

<h1>Home#index</h1>
<% @data.each do |name| %>
  <p style="margin-bottom: 2px;">
    <%unless name["children"].empty? %>
      despliega
      <%= link_to "#{name['name']}", "#", class: "button is-dark" %>
    <% else %>
      <%= link_to "#{name['name']}", "#", class: "button is-dark" %>
    <% end %>
  </p>

  <% name['children'].each do |subname| %>
    <p>second
      <%= subname['name']%>
    </p>
    <% subname['children'].each do |minimalname| %>
      <p>third
        <%= minimalname['name']%>
        <span>
        <%= minimalname['id']%>
      </p>
    <%end%>
  <%end%>
<%end%>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/messages.html.erb
<h1>Home#messages</h1>
<p>Find me in app/views/home/messages.html.erb</p>
<script type="text/javascript">
var button = document.getElementById("notifications");
button.addEventListener('click', function(e) {
    Notification.requestPermission().then(function(result) {
        if(result === 'granted') {
            randomNotification();
        }
    });
});
function randomNotification() {
    var randomItem = Math.floor(Math.random()*games.length);
    var notifTitle = games[randomItem].name;
    var notifBody = 'Created by '+games[randomItem].author+'.';
    var notifImg = 'data/img/'+games[randomItem].slug+'.jpg';
    var options = {
        body: notifBody,
        icon: notifImg
    }
    var notif = new Notification(notifTitle, options);
    setTimeout(randomNotification, 30000);
}
</script>

app/views/home/products.html.erb
<h1>Home#products</h1>
<p>Find me in app/views/home/products.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vink</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <meta name="description" lang="en" content="">
    <meta name="description" lang="es" content="">

    <meta name="apple-mobile-web-app-capable" content="yes">

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <%= yield :stylesheets %>
    <link rel="manifest" href="/manifest.json">
    <script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>
  </head>

  <body class="has-navbar-fixed-top has-navbar-fixed-bottom">
    <nav class="navbar is-fixed-top has-background-white" role="navigation" aria-label="main navigation">
      <div class="columns is-mobile">
        <div class="column has-text-left">
          <%= header_menu_left %>
        </div>
        <div class="column has-text-centered">
          <%= header_title %>
        </div>
        <div class="column has-text-right">
          <%= header_menu_right %>
        </div>
      </div>
    </nav>
    <main class="db-main has-background-warning">
      <%= yield %>
    </main>
    <footer class="has-background-white">
      <div class="columns is-gapless is-mobile">
        <div class="column is-centered">
          <p class="has-background-light">
            <%= link_to appoitments_path, class: "link" do %>
              <span class="icon is-large">
                <i class="fas fa-3x fa-envelope-open-text"></i>
              </span>
            <% end %>
          </p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/products/index.html.erb
<h1>Productos</h1>
<% @products_list.each do |product| %>
  <%= link_to product_path(product['Id']) do %>
    <p>
      <%= image_tag("192x192.png") %>
      <%= product['Name'] %>
    </p>
  <% end %>
<% end %>

app/views/products/show.html.erb
<h1>Detalle de producto</h1>
<%= image_tag("192x192.png") %>
<br>
<%= link_to "Agendar cita", new_appoitment_path, class: "button is-danger"%>
<%= link_to "Lo quiero", "#", class: "button is-danger"%>
<br>
<% @product.each do |detail|  %>
  <% detail.reverse_each do |key, value| %>
      <% if value.is_a?(String) && value != '' %>
        <%= value %>
      <% else %>
        <%= value[0] %>
      <% end %>
    <br>
  <% end %>
<% end %>

app/views/scanner/index.html.erb
<video id="preview" width="100%" height="100%"></video>
<script type="text/javascript">
    var scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
    scanner.addListener('scan', function (content) {
      location.replace(content);
    });
    Instascan.Camera.getCameras().then(function (cameras) {
      if (cameras.length > 0) {
        scanner.stop(cameras[1])
        scanner.start(cameras[1])
      } else {
        alert('No se puede acceder a la camara trasera del movil');
      }
    }).catch(function (e) {
      console.error(e);
    });
</script>

app/views/service_worker/manifest.json.erb
{
  "short_name": "Vink admin",
  "name": "Vink admin",
  "icons": [
    {
      "src": "<%= asset_path('192x192.jpg') %>",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "<%= asset_path('512x512.jpg') %>",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": "<%= root_path %>",
  "background_color": "#fff",
  "display": "standalone",
  "scope": "<%= root_path %>",
  "theme_color": "#f60"
}

app/views/service_worker/offline.html.erb
<div class="user-view view">
  <h1>Parece que has perdido tu conexión a Internet</h1>
  <p>Es posible que deba volver a conectarse a Wi-Fi.</p>
</div>

app/views/service_worker/service_worker.js.erb
var CACHE_VERSION = 'v1';
var CACHE_NAME = CACHE_VERSION + ':sw-cache-';

 function onInstall(event) {
  console.log('[Serviceworker]', "Installing!", event);
  event.waitUntil(
    caches.open(CACHE_NAME).then(function prefill(cache) {
      return cache.addAll([
        '<%= asset_pack_path 'application.js' %>',
        '<%= stylesheet_path 'application.css' %>',
        '/offline.html',
      ]);
    })
  );
}

 function onActivate(event) {
  console.log('[Serviceworker]', "Activating!", event);
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.filter(function(cacheName) {
          // Return true if you want to remove this cache,
          // but remember that caches are shared across
          // the whole origin
          return cacheName.indexOf(CACHE_VERSION) !== 0;
        }).map(function(cacheName) {
          return caches.delete(cacheName);
        })
      );
    })
  );
}

 // Borrowed from https://github.com/TalAter/UpUp
function onFetch(event) {
  event.respondWith(
    // try to return untouched request from network first
    fetch(event.request).catch(function() {
      // if it fails, try to return request from the cache
      return caches.match(event.request).then(function(response) {
        if (response) {
          return response;
        }
        // if not found in cache, return default offline content for navigate requests
        if (event.request.mode === 'navigate' ||
          (event.request.method === 'GET' && event.request.headers.get('accept').includes('text/html'))) {
          console.log('[Serviceworker]', "Fetching offline content", event);
          return caches.match('/offline.html');
        }
      })
    })
  );
}

 self.addEventListener('install', onInstall);
self.addEventListener('activate', onActivate);
self.addEventListener('fetch', onFetch);